### ISSUE TITLE
Column summaries output display for no by factors

### ISSUE THREAD

**Issue by dannyparsons** [IDEMSInternational/R-Instat#5482]
Originally from here #5465 

> With the more general Column Summaries with multiple variables and multiple summaries it gives an awful display in the output window - as it assumes one row and as many columns as there are variables Times summaries. If you save it has a special bug - @dannyparsons knows so only a single number is displayed.
> When there are no factors then could the (default) display be with a variable (column) for the summary and each variable is a row. This could perhaps be an option more generally? That's a stack, but difficult to specify currently manually until we can have groups of variables.

**Comment by rdstern** [comment]
@N-thony I was really worried that Lisa's bug was yet another serious regression, and in a crucial - one of our most important dialogs.  I am very relieved that it is not a regression, and is not so serious.  We should do something about it, but it is only when there are no factors in the dialog.  Then it should give a single row in the resulting data frame.  
A simple and quick "bodge" is to only activate ok when there is one or more factors.

But why not allow no factors?  I suggest:
a) Move the Summaries button into the current place of the Summarise By, so Move Summarise By down a bit.
b) Make Summarise by from a Label into a Checkbox, default Checked.
c) If unchecked then have the up-down control from the Describe > Tables > Summarise dialog, to be able to order the resulting summaries.
d) Then the resulting data frame has a Summaries Variable variable first.  Then there is one variable, with with each same name as the variable in the original sheet.
e) @lilyclements would this be easy to code?

**Comment by rdstern** [comment]
But why not allow no factors? I suggest we consider the following as well, but later:
a) Move the Summaries button into the current place of the Summarise By, so Move Summarise By down a bit.
b) Make Summarise by from a Label into a Checkbox, default Checked.
c) If unchecked then have the up-down control from the Describe > Tables > Summarise dialog, to be able to order the resulting summaries.
d) Then the resulting data frame has a Summaries Variable variable first. Then there is one variable, with with each same name as the variable in the original sheet.
e) @lilyclements would this be easy to code?
f) There are 2 options that don't apply when there are no factors, so they are disabled. They are drop unused levels, and writing back to the original data frame.

**Comment by rdstern** [comment]
@lilyclements after further discussions with @dannyparsons the situation is clear to me - at last!
a) It used to work with no factors, so please couldm you see if there could be an easy correction.  The problem, with no factors, is that apparently the linking doesn't work.  We need a factor column to have a link.
But it apparently used to work - just that, without the linking, a second use of the dialog, like that, would go to a new one-line data frame, because the links are not there.

This should be easy to do, i.e. I assume the big has been introduced, when other changes were made, that it is trying to link and can't do it.  I hope @lilyclements can check on the R code, and then @N-thony or @Vitalis95 or @MeSophie could add the edit, if @lilyclements does not include the addition herself?

A separate "improvement" could be to change the layout of the results - whether there are factors or not.  This could be a checkbox, below the Original Level, saying Summaries as Factor (No Links).  If checked the Original Level becomes unchecked and vv.  You choose none, or one of those options.

Then we don't need any reorder summaries control, because this produces a new factor Variable, called Summary, with the names of each summary as the levels of the factor.  I suggest id there are no factors this becomes the layout, and it is an option if there are factors.  That can come later.

**Comment by rdstern** [comment]
@N-thony I am re-opening, because there are 2 options missed.  One is easy and we only do the second if it is also easy!
a) Here is an option that should work.  It used to work, then it stopped, in version 0.8.0.88 because of the bug (fixed by @lilyclements for this release.) 

![image](https://github.com/user-attachments/assets/6bec61b8-086f-400c-839b-7cb77b8ec9d8)

This option should still work fine, so I suggest all you have to do, is not make it go to the output window for no factors if it has the option chosen to write back to the original level.

b) @N-thony I suspect this may be more difficult - if so, then it is not for now.  There are many more important things.
Could we add an option to save the summaries as scalars, in the original level?  That's what I suggest we do with the calculator.  However the advantage of doing them here is that we make them all with one run of the dialog.  With the calculator, we do them one at a time.

I hope a) can be done for the release next week.  I suspect b) will be later, or never?

**Comment by rdstern** [comment]
@N-thony of course.  As I say above, I hope this can be in the release at the end of next week.  It is no longer a bug, so I have removed that label.

**Comment by rdstern** [comment]
I have now found a serious bug as well.  Not serious enough to stop the build, but certainly to be fixed for next week.
To demonstrate you can use the tutotial_after file that is now in the R-Instat part of the library.
a) From the dodoma sheet complete as shown, (including the missing values checkbox) with the summaries just the mean.

![image](https://github.com/user-attachments/assets/bd36172e-c562-4b9f-9810-d2bf2e0bba5c)

This all works fine so far.

b) Now press `Reset `and then repeat the dialog above, including changing the summaries to just the mean.

It now is different trying to produce the new sheet as shown below.  Note it only produces the first mean in the new one-cell sheet.

![image](https://github.com/user-attachments/assets/b8057e56-7954-469b-9dc6-0a8dcd66b78f)

And, worse than this, dodoma by year has been messed up, with the previous values changed into the mean.

![image](https://github.com/user-attachments/assets/a12541c5-0523-4361-8d16-43b0d572a7c7)

I'm very sorry that I missed this serious problem earleir, in my checking.  I have put the bug label back into the issue.

This is serious.  It is not serious enough to ask for a new version, simply because it is very unlikely to be used by the e-siac participants.  But I am happy it is not going on the web, and we should not publicise it to Lisa at CIMH until it is fixed.

I was delayed and hence did not write yet about this feature in the upgraded help.  I am now releived at the delay!

**Comment by lilyclements** [comment]
@rdstern great find on the bug. I have traced back to 2019 (I cannot easily go further due to differences in changing the name to `data_book`, packages, etc!), and it is still occurring there. Very interesting one!
I wonder if this has always been there, or if it is a funny thing coming in from updating the R version. What is the oldest downloaded version of R-Instat you have and is it occurring there?
