### ISSUE TITLE
Tidy the metadata bottom right-click

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#9357]
There are three items here, either to be taken together, or as separate pull requests.

1. @Fidel365 here is the bottom metadata right-click menu currently:

![image](https://github.com/user-attachments/assets/27bf36f4-42c6-4fbb-ba03-eb7cc66d1943)

You have just tidied the data frame right click from the data window.  I suggest it should be the same from here.

So get rid of the View Data option, and reorder the others so they are identical to the one you tidied earlier.

2. At the same time the option for the R-viewer, in the toolbar, ignores the meta-data window.   Could it either:
a) Show the data for the window - data or metadata - that has the current focus,  Or
b) If that is difficult, then (as now) show the window for the data view, unless that is closed.  If closed, then it shows the data corresponding to the current metadata?
 
3. When implementing the R-viewer from the toolbar it still says:

`# Right click menu: View R Data Frame` in the output window.

Of course it is no longer a Right click menu.  So now it could either say `#Toolbar Option: View R Data Frame`, or just `#View R Data Frame`

Thanks

**Comment by lilyclements** [comment]
Fixed by #9358

**Comment by lilyclements** [comment]
Part 2. needs work on still

**Comment by Ag-Derek** [comment]
@Emmanuel-Afrifa can you take this up?

**Comment by Emmanuel-Afrifa** [comment]
@rdstern 
Please, could elaborate the second issue again. It don't quite understand the issue. 
I'm assuming that by `R-Viewer`, you mean `R-Data Viewer` that can be found in the dropdown list next to the `Toggle Data view open and closed` icon on the toolbar. 

<img width="526" alt="Image" src="https://github.com/user-attachments/assets/9b43d735-d5e2-4741-964e-c5fd0f4f67ab" />

When you click on `R-Data Viewer`, this is the window that shows

<img width="778" alt="Image" src="https://github.com/user-attachments/assets/5fb214ea-dccd-4678-84bb-82ce49eea7b2" />

> At the same time the option for the R-viewer, in the toolbar, ignores the meta-data window. Could it either:
a) Show the data for the window - data or metadata - that has the current focus, Or
b) If that is difficult, then (as now) show the window for the data view, unless that is closed. If closed, then it shows the data corresponding to the current metadata?

Currently, it shows the data frame that's in focus in the data viewer (even if the data viewer is closed).
In cases where the meta data viewer focuses on a different data and the data viewer shows a different data (as seen below), the `R-Data Viewer` still shows the data in focus in the data viewer. 

<img width="686" alt="Image" src="https://github.com/user-attachments/assets/a12aee3f-4818-40ad-9464-127cad6d21a5" />

Is this what you want changed? That's if the data viewer is closed, then should the `R-Data Viewer` show the data in focus in the meta data viewer instead of the one in the data viewer?

**Comment by Emmanuel-Afrifa** [comment]
@lilyclements Oh, I get it now... Based on that I assume the issue is still persistent... I will try and see if I can fix it...
